services:
  db:
    image: mysql
    restart: always
    container_name: inventory_db
    environment:
      MYSQL_ROOT_PASSWORD: P@55w0rd2024
      MYSQL_DATABASE: inventorydb
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
 

  app:
    image: inventory-lite
    container_name: inventory_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    volumes:
      - .:/app
    depends_on:
      - db


volumes:
  db_data:
    driver: local